export const noticies = [
            {
              "_id": "63f8a8a3012ecaaf04vefve",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
            },
            {
              "_id": "63f8a8a3012ecaaf049bvnnt",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
             {
              "_id": "63f8a8a3012ecaaf04brgbrb",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
              {
              "_id": "63f8a8a3012ecaaf049bhntnt",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
               {
              "_id": "63f8a8a3012ecaaf049bdvdvd5",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                {
              "_id": "63f8a8a3012evdfbaf049b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                 {
              "_id": "63f8a8a3012ecaafdfbdd8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                  {
              "_id": "63f8a8a30vdfbcaaf049b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                   {
              "_id": "63f8a8a3012ecaaddbd335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                    {
              "_id": "63f8a8a3svssdvv49b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                     {
              "_id": "63f8a8a3012ecaaf04sdvsvs335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                      {
              "_id": "63f8a8a3012esdvsvf049b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                       {
              "_id": "63f8a8a3012ecacsdcsc49b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://www.pexels.com/photo/monochrome-photo-of-tabby-cat-2527491/",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
  },
                        {
              "_id": "63f8a8a3012ecsdccsdcs49b8335",
                "breed": "Bengal",
                "comments":"Active toactive",
                "title": "Kitten for sale",
                "price":"for-free",
                "category": "sell",
                "avatarURL": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "male",
            },
];
