export const noticies = [
  {
    _id: '63f8a8a3012ecaaf04vefve',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten',
    price: '200',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.21',
    sex: 'female',
  },
  {
    _id: '63f8a8a3012ecaaf049bvnnt',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Cat',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.01.21',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaaf04brgbrb',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaaf049bhntnt',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.03.18',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaaf049bdvdvd5',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012evdfbaf049b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: 'g',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaafdfbdd8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a30vdfbcaaf049b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaaddbd335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3svssdvv49b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecaaf04sdvsvs335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012esdvsvf049b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecacsdcsc49b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
  {
    _id: '63f8a8a3012ecsdccsdcs49b8335',
    breed: 'Bengal',
    comments: 'Active toactive',
    title: 'Kitten for sale',
    price: 'for-free',
    category: 'sell',
    avatarURL: '',
    location: 'Lviv',
    date: '07.09.22',
    sex: 'male',
  },
];
